### ISSUE TITLE
Cannot build on version 2.6.2.2

### ISSUE THREAD

**Issue by kaonn** [nad/equality#1]
Hi,

I'm having some trouble getting this library to build on Agda version 2.6.2.2. 
Specifically some constraints cannot be solved in https://github.com/nad/equality/blob/master/src/Equivalence/Contractible-preimages.agda 
It seems like the problem is unresolved metas in the definitions https://github.com/nad/equality/blob/b60c3f781a81d5ed9fe1debe02dda01bed643c6d/src/Equivalence/Contractible-preimages.agda#L54 and https://github.com/nad/equality/blob/b60c3f781a81d5ed9fe1debe02dda01bed643c6d/src/Equivalence/Contractible-preimages.agda#L59 

Would appreciate any help in getting this to build.

**Comment by nad** [comment]
The library uses the option `--erased-cubical`, which is not available in Agda 2.6.2.2. A recent development version of Agda (2.6.3-5d2d77a) works for me.
